shared: &shared
  :paperclip:
    :url_pattern: '/system/:class/:attachment/:id/:style/:basename.:extension'
    :path_pattern: ':rails_root/public/system/:class/:attachment/:id/:style/:basename.:extension'
    :command_path: /usr/local/bin
    :valid_image_formats:
      - png
      - jpg
    :valid_image_content_types:
      - image/png
      - image/jpg
      - image/jpeg
development:
  <<: *shared

test:
  <<: *shared

cucumber:
  <<: *shared

staging:
  <<: *shared
  :paperclip:
    :command_path: /usr/bin

production:
  <<: *shared
  :paperclip:
    :command_path: /usr/bin
