--- 
javascripts: 
- base: 
  - jquery
  - jquery.easing
  - application
- admin: 
  - admin/jquery
  - admin/jquery.ui
  - admin/jquery.tablednd
  - admin/jquery.form
  - admin/jquery.validate
  - admin/application
stylesheets:
- base:
  - reset
  - foundation
  - application
- admin:
  - reset
  - foundation
  - admin/master
