--- 
javascripts: 
- base: 
  - jquery
  - jquery.easing
  - application
- admin: 
  - admin/jquery-1.3.1
  - admin/jquery-ui-personalized-1.5.3
  - admin/jquery.livequery
  - admin/jquery.tablednd.0.5
  - admin/jquery.form
  - admin/jquery.validate
  - admin/application
stylesheets:
- base:
  - reset
  - foundation
  - application
- admin:
  - reset
  - foundation
  - admin/master
